
    
    
def db_create_matches_for_round(tournament_id, roundnum, winnerlist):
    amount_of_seeds = len(winnerlist)
    
    # shuffle the list
    random.shuffle(winnerlist)
    
    for each in grouper(winnerlist, 2, 0):
      db_create_match(tournament_id, roundnum, each[0], each[1], 'Autogenerated match')
      
def db_create_player_participant(player_id, tournament_id):  
    tt = TournamentTeam()
    tt.save()
  
    pp = PlayerParticipant()
    pp.player = Player.objects.get(id__exact=player_id)
    pp.tournament = Tournament.objects.get(id__exact=tournament_id)
    pp.team = tt
    pp.save()
    

    
    
  
  
  
  

